version: '3.1'
services:
  postgres-db:
    image: postgres:14-alpine
    container_name: postgres-db
    volumes:
      - ./postgres-db/data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: on-failure
    environment:
      POSTGRES_DB: public
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --lc-collate=C --lc-ctype=C'
    networks:
      internal:

  application:
    build: .
    container_name: application
    depends_on:
      postgres-db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 512M
    environment:
      JAVA_OPTS: >-
        -Xms500M
        -Xmx500M
        -Dfile.encoding=UTF-8
        -Duser.country=RU
        -Duser.language=ru
        -Duser.timezone=Europe/Moscow
        -XX:+UseG1GC
        -XX:ActiveProcessorCount=2
        -XX:+AlwaysActAsServerClassMachine
      DATASOURCE_MAIN_DB_HOST: db
      DATASOURCE_MAIN_DB_PORT: 5432
      DATASOURCE_MAIN_DB_database: public
      DATASOURCE_MAIN_DB_JDBC_URL: jdbc:postgresql://db:5432/public
      DATASOURCE_MAIN_DB_USERNAME: user
      DATASOURCE_MAIN_DB_PASSWORD: password
    networks:
      internal:

networks:
  internal:
